name: Deploy to VM and Dockerize

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into VM and update code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd kansas/SER516-Team-Kansas
          git pull origin main

    - name: Turning down the containers
      run: docker-compose down

    - name: Delete all old containers
      run: docker-compose rm -f

    - name: Build and run new containers from new images
      run: docker-compose up --build -d
